objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory:
    centreon_inventory_host:
      description: Centreon host inventory source
      name: centreon_inventory_host
      version_added: null
  lookup: {}
  module:
    add_host_group:
      description: Add a new host group configuration
      name: add_host_group
      namespace: ''
      version_added: null
    create_host_category:
      description: Create a host category
      name: create_host_category
      namespace: ''
      version_added: null
    create_host_configuration:
      description: Create a host configuration
      name: create_host_configuration
      namespace: ''
      version_added: null
    create_host_severity:
      description: Create a host configuration
      name: create_host_severity
      namespace: ''
      version_added: null
    delete_host_category:
      description: Delete a host category configuration
      name: delete_host_category
      namespace: ''
      version_added: null
    delete_host_configuration:
      description: Delete a host configuration
      name: delete_host_configuration
      namespace: ''
      version_added: null
    delete_host_group:
      description: Delete host group
      name: delete_host_group
      namespace: ''
      version_added: null
    delete_host_severity:
      description: Delete a host severity configuration
      name: delete_host_severity
      namespace: ''
      version_added: null
    delete_service_category:
      description: Delete a service category configuration
      name: delete_service_category
      namespace: ''
      version_added: null
    find_all_host_configurations:
      description: Return all host configurations.
      name: find_all_host_configurations
      namespace: ''
      version_added: null
    find_all_host_template_configurations:
      description: Return all host template configurations.
      name: find_all_host_template_configurations
      namespace: ''
      version_added: null
    generate_configuration_all_monitoring_server:
      description: Generate and move the configuration files for all monitoring servers.
      name: generate_configuration_all_monitoring_server
      namespace: ''
      version_added: null
    generate_configuration_monitoring_server:
      description: Generate and move the configuration files of the monitoring server
      name: generate_configuration_monitoring_server
      namespace: ''
      version_added: null
    generate_reload_configuration_all_monitoring_server:
      description: Generate, move and reload the configuration files for all monitoring
        servers.
      name: generate_reload_configuration_all_monitoring_server
      namespace: ''
      version_added: null
    generate_reload_configuration_monitoring_server:
      description: Generate, move and reload the configuration files of the monitoring
        server
      name: generate_reload_configuration_monitoring_server
      namespace: ''
      version_added: null
    get_host_category:
      description: Get a host category configuration
      name: get_host_category
      namespace: ''
      version_added: null
    get_host_group:
      description: Get an existing host group.
      name: get_host_group
      namespace: ''
      version_added: null
    get_host_severity:
      description: Get a host severity configuration
      name: get_host_severity
      namespace: ''
      version_added: null
    list_all_host_categories:
      description: List of host category configurations
      name: list_all_host_categories
      namespace: ''
      version_added: null
    list_all_host_groups:
      description: Return all host group configurations.
      name: list_all_host_groups
      namespace: ''
      version_added: null
    list_all_host_severities:
      description: List of all host severity configurations
      name: list_all_host_severities
      namespace: ''
      version_added: null
    list_all_monitoring_servers_configurations:
      description: List all monitoring servers configurations.
      name: list_all_monitoring_servers_configurations
      namespace: ''
      version_added: null
    manage_host:
      description: Manage host in Centreon via API v2
      name: manage_host
      namespace: ''
      version_added: null
    manage_host_groups:
      description: Create a host in Centreon via API v2
      name: manage_host_groups
      namespace: ''
      version_added: null
    partially_update_host_configuration:
      description: Partially update a host configuration.
      name: partially_update_host_configuration
      namespace: ''
      version_added: null
    reload_configuration_all_monitoring_server:
      description: Reload the configuration files for all monitoring servers.
      name: reload_configuration_all_monitoring_server
      namespace: ''
      version_added: null
    reload_configuration_monitoring_server:
      description: Reload the configuration files of the monitoring server
      name: reload_configuration_monitoring_server
      namespace: ''
      version_added: null
    update_host_category:
      description: Update a host severity
      name: update_host_category
      namespace: ''
      version_added: null
    update_host_group:
      description: Update host group.
      name: update_host_group
      namespace: ''
      version_added: null
    update_host_severity:
      description: Update a host severity
      name: update_host_severity
      namespace: ''
      version_added: null
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.5.0
